### ISSUE TITLE
Merge branch

### ISSUE THREAD

**Issue by ionuorah** [positivemuon/aiida-impuritysupercellconv#2]
Merge the development branch and update documentation before submission

 [GP: I just real-
ized the repo has changed name to this, but the python
package is still aiida musconv? (at least in the main
branch) This is going to be confusing, no? Is this planned
to be changed? If it’s in a differnt branch, we should try
to merge in the main branch before submitting the paper]

**Comment by mikibonacci** [comment]
done with this commit: https://github.com/positivemuon/aiida-impuritysupercellconv/commit/83a25a555179d0bca690f3110ddd03c4b426845b
